version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - vet_appointment_manager_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  vet_appointment_manager_db:
